### PR TITLE
Added an "initiated" flag

### PR DESCRIPTION
**Pull request by sirmonin**

### CODE REVIEW

**Comment by sirmonin** [comment]
#265

**Comment by zhaohong** [comment]
thanks!

**Review by C201808 — APPROVED** [review]

**Comment by sirmonin** [comment]
@zk19862018 
Why is this closed?
In our project we need to define whether user has following conditions:
1) TronLink not installed
2) TronLink installed and logged in
3) TronLink installed and not logged in

We previously checked 3rd condition by checking window.tronWeb and !window.tronWeb.ready.
But sometimes, logged in state (window.tronWeb.ready) just didn't set on time, and app shows 3rd state, even if user is logged in.
Because logging into TronLink, when pageHook.js loads is an async task.
And we cannot know, when logged in setting (or not) is finished.
So we need to know exactly if tronWeb is initiated (logging in has passed).
Currently we do this by catching the "TronLink initiated" log message, which is a bad but the only solution. (adding a timeout before check on clients code is not robust too).
I am sure this "initiated flag" will be useful not only for our project, but also for other projects, to clearly define initiated state of TronLink.

Even setting window.tronWeb.ready to false (instead of remaining undefined) in case user is not logged in would help

**Comment by sirmonin** [comment]
Even setting window.tronWeb.ready to false (instead of remaining undefined) in case user is not logged in would help

**Comment by zk19862018** [comment]
@sirmonin 
By adding "tronweb.initiated = true" in method "init()" in pageHook.js can not solve the three points you concern.

Even you does not login in tronlink, after you installed the tronlink, tronweb.initiated you get is true. 

1. TronLink not installed
 
const tronWeb = window.tronWeb;
    if (!tronWeb) {
    // tronlink is not installed
    }

2. TronLink installed and logged in

 const address = tronWeb.defaultAddress.base58;
    if (address) {
      // tronlink is installed and login
    }

3. TronLink installed and not logged in

 const address = tronWeb.defaultAddress.base58;
    if (!address) {
      // tronlink is installed and not login
    }

**Comment by sirmonin** [comment]
@zk19862018 
> Even you does not login in tronlink, after you installed the tronlink, tronweb.initiated you get is true.

That's actually the needed point. I need to know when pageHook.js has finished to execute, in order to perform checks to distinguish logged-in/logged-out state.

From your previous message: yes, as I described, we can do it in this way. But the problem is, when we check if (address) or if(!address), the check itself can execute **before** `this.setAddress({address,name,type});` (row 28 from pageHook.js) is executed.
The case we've ran into was, that user is logged in to tronlink, but defaultAddress.base58 was empty at the moment we've checked it. 

The time which takes pageHook.js to load and perform all it initial methods always differs (network, pc performance etc.) and is not predictable by default.

We just need a flag or an event, that will allow us to know when exactly we can perform logged-in state check and other logic.

We surely can set a timeout for check from our side, but it will increase before-interaction-is-possible-time and won't guarantee that this timeout would be enough.

**Pull request closed without merging**
